### ISSUE TITLE
Map back reads to assembly

### ISSUE THREAD

**Issue by erikrikarddaniel** [LNUc-EEMiS/metatdenovo-dsl1#5]
Map back QCed reads to each assembly. Make sure output is sorted bam files.

**Comment by DiegoBrambilla** [comment]
I am thinking of a single process that takes care of both the mapping and the sorting.
Speaking of bacteria metagenomes, Bowtie2 and SAMtools can be used.
I suggest following the guidelines in [makefile.bowte2](https://github.com/erikrikarddaniel/biomakefiles/blob/master/lib/make/makefile.bowtie2) (refer to rules [all_bowte2indeces](https://github.com/erikrikarddaniel/biomakefiles/blob/master/lib/make/makefile.bowtie2#L114) and [all_pe_sorted_bams](https://github.com/erikrikarddaniel/biomakefiles/blob/master/lib/make/makefile.bowtie2#L51)).

Coverage could be obtained through BEDTools by following the [method in Andrea Franzetti's pipeline](https://gitlab.com/Diego_Brambilla/icme9/-/blob/icme9_arg/script_coassembly_arg.sh#L64-80).

**Comment by erikrikarddaniel** [comment]
Yes, one process that maps one pair of fastq files to the contigs of one assembly. Build a command line pipeline like the one in the makefile.bowtie2 you mention. The actual quantification is one or more later steps, possibly with SAMtools, BEDtools, htseq or subread, depending on whether it's the contig in its entirety or and individual ORF that's quantified.

**Comment by DiegoBrambilla** [comment]
Reporting here advices from Harshil Patel (nf-core team):
staging indices on AWS is tricky because some aligners typically require the path to an index including a prefix. (edited) 
You can't just give the full path to the index including the prefix because all of the other files in the index won't be staged that way.
As far as I am aware, there have been two robust solutions (and tested on AWS) here on nf-core. One that I have been using in the pipelines I have written (atacseq, chipseq, viralrecon; the latter also uses bowtie2) and one that @Maxime Garcia has been using in Sarek.
At the last nf-core Hackathon we agreed to use the method used in sarek because these sorts of discrepancies will need to be ironed out if and when we need to standardise pipelines for porting to nf-core/modules.
To give you an example for bwa mem , below is the module file for building an index:
https://github.com/nf-core/modules/blob/master/software/bwa/index/main.nf (edited) 
and another one to run bwa mem :
https://github.com/nf-core/modules/blob/master/software/bwa/mem/main.nf (edited) 
If you want to provide a pre-build index on the command-line using a parameter e.g. --bwa_index then you can use the format below:
https://github.com/nf-core/chipseq/blob/ee7c9f582ca99272e1a6e1f6006643254a3d9cdf/conf/igenomes.config#L15

**Comment by erikrikarddaniel** [comment]
Let's do "quantification" with potentially different implementations, see issue #17.
